package com.trip.entity;

public class Business {

    private Integer businessId;
    private String loginName;
    private String password;
    private String businessName;
    private String tel;
    private String address;
    private Double score;
    private Integer monthlySales;
    private Integer businessType;   //商家类型，1-美食，2-娱乐，3-衣服
    private String expContent1;
    private String expContent2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.business_id
     *
     * @return the value of business.business_id
     *
     * @mbggenerated Sun Dec 24 20:40:23 CST 2017
     */
    public Integer getBusinessId() {
        return businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.business_id
     *
     * @param businessId the value for business.business_id
     *
     * @mbggenerated Sun Dec 24 20:40:23 CST 2017
     */
    public void setBusinessId(Integer businessId) {
        this.businessId = businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.login_name
     *
     * @return the value of business.login_name
     *
     * @mbggenerated Sun Dec 24 20:40:23 CST 2017
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.login_name
     *
     * @param loginName the value for business.login_name
     *
     * @mbggenerated Sun Dec 24 20:40:23 CST 2017
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName == null ? null : loginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.password
     *
     * @return the value of business.password
     *
     * @mbggenerated Sun Dec 24 20:40:23 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.password
     *
     * @param password the value for business.password
     *
     * @mbggenerated Sun Dec 24 20:40:23 CST 2017
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.business_name
     *
     * @return the value of business.business_name
     *
     * @mbggenerated Sun Dec 24 20:40:23 CST 2017
     */
    public String getBusinessName() {
        return businessName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.business_name
     *
     * @param businessName the value for business.business_name
     *
     * @mbggenerated Sun Dec 24 20:40:23 CST 2017
     */
    public void setBusinessName(String businessName) {
        this.businessName = businessName == null ? null : businessName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.tel
     *
     * @return the value of business.tel
     *
     * @mbggenerated Sun Dec 24 20:40:23 CST 2017
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.tel
     *
     * @param tel the value for business.tel
     *
     * @mbggenerated Sun Dec 24 20:40:23 CST 2017
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.address
     *
     * @return the value of business.address
     *
     * @mbggenerated Sun Dec 24 20:40:23 CST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.address
     *
     * @param address the value for business.address
     *
     * @mbggenerated Sun Dec 24 20:40:23 CST 2017
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.score
     *
     * @return the value of business.score
     *
     * @mbggenerated Sun Dec 24 20:40:23 CST 2017
     */
    public Double getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.score
     *
     * @param score the value for business.score
     *
     * @mbggenerated Sun Dec 24 20:40:23 CST 2017
     */
    public void setScore(Double score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.monthly_sales
     *
     * @return the value of business.monthly_sales
     *
     * @mbggenerated Sun Dec 24 20:40:23 CST 2017
     */
    public Integer getMonthlySales() {
        return monthlySales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.monthly_sales
     *
     * @param monthlySales the value for business.monthly_sales
     *
     * @mbggenerated Sun Dec 24 20:40:23 CST 2017
     */
    public void setMonthlySales(Integer monthlySales) {
        this.monthlySales = monthlySales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.business_type
     *
     * @return the value of business.business_type
     *
     * @mbggenerated Sun Dec 24 20:40:23 CST 2017
     */
    public Integer getBusinessType() {
        return businessType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.business_type
     *
     * @param businessType the value for business.business_type
     *
     * @mbggenerated Sun Dec 24 20:40:23 CST 2017
     */
    public void setBusinessType(Integer businessType) {
        this.businessType = businessType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.exp_content1
     *
     * @return the value of business.exp_content1
     *
     * @mbggenerated Sun Dec 24 20:40:23 CST 2017
     */
    public String getExpContent1() {
        return expContent1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.exp_content1
     *
     * @param expContent1 the value for business.exp_content1
     *
     * @mbggenerated Sun Dec 24 20:40:23 CST 2017
     */
    public void setExpContent1(String expContent1) {
        this.expContent1 = expContent1 == null ? null : expContent1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.exp_content2
     *
     * @return the value of business.exp_content2
     *
     * @mbggenerated Sun Dec 24 20:40:23 CST 2017
     */
    public String getExpContent2() {
        return expContent2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.exp_content2
     *
     * @param expContent2 the value for business.exp_content2
     *
     * @mbggenerated Sun Dec 24 20:40:23 CST 2017
     */
    public void setExpContent2(String expContent2) {
        this.expContent2 = expContent2 == null ? null : expContent2.trim();
    }
}