package com.trip.entity;

import java.io.Serializable;
import java.util.List;

public class Commodity implements Serializable{


    private Integer commodityId;

    private String commodityName;

    private Double price;

    private String detail;

    private Integer monthlySales;

    private Integer storeId;

    private List<String> imageUrls;

    private String expContent1;

    private String expContent2;


    public Integer getCommodityId() {
        return commodityId;
    }

    public void setCommodityId(Integer commodityId) {
        this.commodityId = commodityId;
    }

    public String getCommodityName() {
        return commodityName;
    }

    public List<String> getImageUrls() {
        return imageUrls;
    }

    public void setImageUrls(List<String> imageUrls) {
        this.imageUrls = imageUrls;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_commodity.commodity_name
     *
     * @param commodityName the value for tb_commodity.commodity_name
     *
     * @mbggenerated Wed Dec 27 14:47:41 CST 2017
     */
    public void setCommodityName(String commodityName) {
        this.commodityName = commodityName == null ? null : commodityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_commodity.price
     *
     * @return the value of tb_commodity.price
     *
     * @mbggenerated Wed Dec 27 14:47:41 CST 2017
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_commodity.price
     *
     * @param price the value for tb_commodity.price
     *
     * @mbggenerated Wed Dec 27 14:47:41 CST 2017
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_commodity.detail
     *
     * @return the value of tb_commodity.detail
     *
     * @mbggenerated Wed Dec 27 14:47:41 CST 2017
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_commodity.detail
     *
     * @param detail the value for tb_commodity.detail
     *
     * @mbggenerated Wed Dec 27 14:47:41 CST 2017
     */
    public void setDetail(String detail) {
        this.detail = detail == null ? null : detail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_commodity.monthly_sales
     *
     * @return the value of tb_commodity.monthly_sales
     *
     * @mbggenerated Wed Dec 27 14:47:41 CST 2017
     */
    public Integer getMonthlySales() {
        return monthlySales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_commodity.monthly_sales
     *
     * @param monthlySales the value for tb_commodity.monthly_sales
     *
     * @mbggenerated Wed Dec 27 14:47:41 CST 2017
     */
    public void setMonthlySales(Integer monthlySales) {
        this.monthlySales = monthlySales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_commodity.store_id
     *
     * @return the value of tb_commodity.store_id
     *
     * @mbggenerated Wed Dec 27 14:47:41 CST 2017
     */
    public Integer getStoreId() {
        return storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_commodity.store_id
     *
     * @param storeId the value for tb_commodity.store_id
     *
     * @mbggenerated Wed Dec 27 14:47:41 CST 2017
     */
    public void setStoreId(Integer storeId) {
        this.storeId = storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_commodity.exp_content1
     *
     * @return the value of tb_commodity.exp_content1
     *
     * @mbggenerated Wed Dec 27 14:47:41 CST 2017
     */
    public String getExpContent1() {
        return expContent1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_commodity.exp_content1
     *
     * @param expContent1 the value for tb_commodity.exp_content1
     *
     * @mbggenerated Wed Dec 27 14:47:41 CST 2017
     */
    public void setExpContent1(String expContent1) {
        this.expContent1 = expContent1 == null ? null : expContent1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_commodity.exp_content2
     *
     * @return the value of tb_commodity.exp_content2
     *
     * @mbggenerated Wed Dec 27 14:47:41 CST 2017
     */
    public String getExpContent2() {
        return expContent2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_commodity.exp_content2
     *
     * @param expContent2 the value for tb_commodity.exp_content2
     *
     * @mbggenerated Wed Dec 27 14:47:41 CST 2017
     */
    public void setExpContent2(String expContent2) {
        this.expContent2 = expContent2 == null ? null : expContent2.trim();
    }
}