package com.trip.entity;

public class Image {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_image.image_id
     *
     * @mbggenerated Fri Dec 29 11:26:16 CST 2017
     */
    private Integer imageId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_image.url
     *
     * @mbggenerated Fri Dec 29 11:26:16 CST 2017
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_image.image_name
     *
     * @mbggenerated Fri Dec 29 11:26:16 CST 2017
     */
    private String imageName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_image.store_id
     *
     * @mbggenerated Fri Dec 29 11:26:16 CST 2017
     */
    private Integer storeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_image.commodity_id
     *
     * @mbggenerated Fri Dec 29 11:26:16 CST 2017
     */
    private Integer commodityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_image.restaurant_id
     *
     * @mbggenerated Fri Dec 29 11:26:16 CST 2017
     */
    private Integer restaurantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_image.dishes_id
     *
     * @mbggenerated Fri Dec 29 11:26:16 CST 2017
     */
    private Integer dishesId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_image.viewpoint_id
     *
     * @mbggenerated Fri Dec 29 11:26:16 CST 2017
     */
    private Integer viewpointId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_image.exp_content1
     *
     * @mbggenerated Fri Dec 29 11:26:16 CST 2017
     */
    private String expContent1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_image.exp_content2
     *
     * @mbggenerated Fri Dec 29 11:26:16 CST 2017
     */
    private String expContent2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_image.image_id
     *
     * @return the value of tb_image.image_id
     *
     * @mbggenerated Fri Dec 29 11:26:16 CST 2017
     */
    public Integer getImageId() {
        return imageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_image.image_id
     *
     * @param imageId the value for tb_image.image_id
     *
     * @mbggenerated Fri Dec 29 11:26:16 CST 2017
     */
    public void setImageId(Integer imageId) {
        this.imageId = imageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_image.url
     *
     * @return the value of tb_image.url
     *
     * @mbggenerated Fri Dec 29 11:26:16 CST 2017
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_image.url
     *
     * @param url the value for tb_image.url
     *
     * @mbggenerated Fri Dec 29 11:26:16 CST 2017
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_image.image_name
     *
     * @return the value of tb_image.image_name
     *
     * @mbggenerated Fri Dec 29 11:26:16 CST 2017
     */
    public String getImageName() {
        return imageName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_image.image_name
     *
     * @param imageName the value for tb_image.image_name
     *
     * @mbggenerated Fri Dec 29 11:26:16 CST 2017
     */
    public void setImageName(String imageName) {
        this.imageName = imageName == null ? null : imageName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_image.store_id
     *
     * @return the value of tb_image.store_id
     *
     * @mbggenerated Fri Dec 29 11:26:16 CST 2017
     */
    public Integer getStoreId() {
        return storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_image.store_id
     *
     * @param storeId the value for tb_image.store_id
     *
     * @mbggenerated Fri Dec 29 11:26:16 CST 2017
     */
    public void setStoreId(Integer storeId) {
        this.storeId = storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_image.commodity_id
     *
     * @return the value of tb_image.commodity_id
     *
     * @mbggenerated Fri Dec 29 11:26:16 CST 2017
     */
    public Integer getCommodityId() {
        return commodityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_image.commodity_id
     *
     * @param commodityId the value for tb_image.commodity_id
     *
     * @mbggenerated Fri Dec 29 11:26:16 CST 2017
     */
    public void setCommodityId(Integer commodityId) {
        this.commodityId = commodityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_image.restaurant_id
     *
     * @return the value of tb_image.restaurant_id
     *
     * @mbggenerated Fri Dec 29 11:26:16 CST 2017
     */
    public Integer getRestaurantId() {
        return restaurantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_image.restaurant_id
     *
     * @param restaurantId the value for tb_image.restaurant_id
     *
     * @mbggenerated Fri Dec 29 11:26:16 CST 2017
     */
    public void setRestaurantId(Integer restaurantId) {
        this.restaurantId = restaurantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_image.dishes_id
     *
     * @return the value of tb_image.dishes_id
     *
     * @mbggenerated Fri Dec 29 11:26:16 CST 2017
     */
    public Integer getDishesId() {
        return dishesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_image.dishes_id
     *
     * @param dishesId the value for tb_image.dishes_id
     *
     * @mbggenerated Fri Dec 29 11:26:16 CST 2017
     */
    public void setDishesId(Integer dishesId) {
        this.dishesId = dishesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_image.viewpoint_id
     *
     * @return the value of tb_image.viewpoint_id
     *
     * @mbggenerated Fri Dec 29 11:26:16 CST 2017
     */
    public Integer getViewpointId() {
        return viewpointId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_image.viewpoint_id
     *
     * @param viewpointId the value for tb_image.viewpoint_id
     *
     * @mbggenerated Fri Dec 29 11:26:16 CST 2017
     */
    public void setViewpointId(Integer viewpointId) {
        this.viewpointId = viewpointId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_image.exp_content1
     *
     * @return the value of tb_image.exp_content1
     *
     * @mbggenerated Fri Dec 29 11:26:16 CST 2017
     */
    public String getExpContent1() {
        return expContent1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_image.exp_content1
     *
     * @param expContent1 the value for tb_image.exp_content1
     *
     * @mbggenerated Fri Dec 29 11:26:16 CST 2017
     */
    public void setExpContent1(String expContent1) {
        this.expContent1 = expContent1 == null ? null : expContent1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_image.exp_content2
     *
     * @return the value of tb_image.exp_content2
     *
     * @mbggenerated Fri Dec 29 11:26:16 CST 2017
     */
    public String getExpContent2() {
        return expContent2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_image.exp_content2
     *
     * @param expContent2 the value for tb_image.exp_content2
     *
     * @mbggenerated Fri Dec 29 11:26:16 CST 2017
     */
    public void setExpContent2(String expContent2) {
        this.expContent2 = expContent2 == null ? null : expContent2.trim();
    }
}