package com.trip.entity;

import java.io.Serializable;

public class Ticket implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_ticket.ticket_id
     *
     * @mbggenerated Wed Dec 27 16:30:27 CST 2017
     */
    private Integer ticketId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_ticket.ticket_name
     *
     * @mbggenerated Wed Dec 27 16:30:27 CST 2017
     */
    private String ticketName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_ticket.price
     *
     * @mbggenerated Wed Dec 27 16:30:27 CST 2017
     */
    private Double price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_ticket.instruction
     *
     * @mbggenerated Wed Dec 27 16:30:27 CST 2017
     */
    private String instruction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_ticket.viewpoint_id
     *
     * @mbggenerated Wed Dec 27 16:30:27 CST 2017
     */
    private Integer viewpointId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_ticket.exp_content1
     *
     * @mbggenerated Wed Dec 27 16:30:27 CST 2017
     */
    private String expContent1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_ticket.exp_content2
     *
     * @mbggenerated Wed Dec 27 16:30:27 CST 2017
     */
    private String expContent2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_ticket.ticket_id
     *
     * @return the value of tb_ticket.ticket_id
     *
     * @mbggenerated Wed Dec 27 16:30:27 CST 2017
     */
    public Integer getTicketId() {
        return ticketId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_ticket.ticket_id
     *
     * @param ticketId the value for tb_ticket.ticket_id
     *
     * @mbggenerated Wed Dec 27 16:30:27 CST 2017
     */
    public void setTicketId(Integer ticketId) {
        this.ticketId = ticketId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_ticket.ticket_name
     *
     * @return the value of tb_ticket.ticket_name
     *
     * @mbggenerated Wed Dec 27 16:30:27 CST 2017
     */
    public String getTicketName() {
        return ticketName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_ticket.ticket_name
     *
     * @param ticketName the value for tb_ticket.ticket_name
     *
     * @mbggenerated Wed Dec 27 16:30:27 CST 2017
     */
    public void setTicketName(String ticketName) {
        this.ticketName = ticketName == null ? null : ticketName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_ticket.price
     *
     * @return the value of tb_ticket.price
     *
     * @mbggenerated Wed Dec 27 16:30:27 CST 2017
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_ticket.price
     *
     * @param price the value for tb_ticket.price
     *
     * @mbggenerated Wed Dec 27 16:30:27 CST 2017
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_ticket.instruction
     *
     * @return the value of tb_ticket.instruction
     *
     * @mbggenerated Wed Dec 27 16:30:27 CST 2017
     */
    public String getInstruction() {
        return instruction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_ticket.instruction
     *
     * @param instruction the value for tb_ticket.instruction
     *
     * @mbggenerated Wed Dec 27 16:30:27 CST 2017
     */
    public void setInstruction(String instruction) {
        this.instruction = instruction == null ? null : instruction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_ticket.viewpoint_id
     *
     * @return the value of tb_ticket.viewpoint_id
     *
     * @mbggenerated Wed Dec 27 16:30:27 CST 2017
     */
    public Integer getViewpointId() {
        return viewpointId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_ticket.viewpoint_id
     *
     * @param viewpointId the value for tb_ticket.viewpoint_id
     *
     * @mbggenerated Wed Dec 27 16:30:27 CST 2017
     */
    public void setViewpointId(Integer viewpointId) {
        this.viewpointId = viewpointId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_ticket.exp_content1
     *
     * @return the value of tb_ticket.exp_content1
     *
     * @mbggenerated Wed Dec 27 16:30:27 CST 2017
     */
    public String getExpContent1() {
        return expContent1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_ticket.exp_content1
     *
     * @param expContent1 the value for tb_ticket.exp_content1
     *
     * @mbggenerated Wed Dec 27 16:30:27 CST 2017
     */
    public void setExpContent1(String expContent1) {
        this.expContent1 = expContent1 == null ? null : expContent1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_ticket.exp_content2
     *
     * @return the value of tb_ticket.exp_content2
     *
     * @mbggenerated Wed Dec 27 16:30:27 CST 2017
     */
    public String getExpContent2() {
        return expContent2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_ticket.exp_content2
     *
     * @param expContent2 the value for tb_ticket.exp_content2
     *
     * @mbggenerated Wed Dec 27 16:30:27 CST 2017
     */
    public void setExpContent2(String expContent2) {
        this.expContent2 = expContent2 == null ? null : expContent2.trim();
    }
}