package com.trip.entity;

import java.io.Serializable;
import java.util.List;

public class Viewpoint implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_viewpoint.viewpoint_id
     *
     * @mbggenerated Wed Dec 27 16:30:27 CST 2017
     */
    private Integer viewpointId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_viewpoint.viewpoint_name
     *
     * @mbggenerated Wed Dec 27 16:30:27 CST 2017
     */
    private String viewpointName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_viewpoint.star_level
     *
     * @mbggenerated Wed Dec 27 16:30:27 CST 2017
     */
    private String starLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_viewpoint.score
     *
     * @mbggenerated Wed Dec 27 16:30:27 CST 2017
     */
    private Double score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_viewpoint.address
     *
     * @mbggenerated Wed Dec 27 16:30:27 CST 2017
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_viewpoint.introduction
     *
     * @mbggenerated Wed Dec 27 16:30:27 CST 2017
     */
    private String introduction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_viewpoint.note
     *
     * @mbggenerated Wed Dec 27 16:30:27 CST 2017
     */
    private String note;

    private List<String> imageUrls;

    private List<Ticket> tickets;

    private List<Route> routes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_viewpoint.exp_content1
     *
     * @mbggenerated Wed Dec 27 16:30:27 CST 2017
     */
    private String expContent1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_viewpoint.exp_content2
     *
     * @mbggenerated Wed Dec 27 16:30:27 CST 2017
     */
    private String expContent2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_viewpoint.viewpoint_id
     *
     * @return the value of tb_viewpoint.viewpoint_id
     *
     * @mbggenerated Wed Dec 27 16:30:27 CST 2017
     */
    public Integer getViewpointId() {
        return viewpointId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_viewpoint.viewpoint_id
     *
     * @param viewpointId the value for tb_viewpoint.viewpoint_id
     *
     * @mbggenerated Wed Dec 27 16:30:27 CST 2017
     */
    public void setViewpointId(Integer viewpointId) {
        this.viewpointId = viewpointId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_viewpoint.viewpoint_name
     *
     * @return the value of tb_viewpoint.viewpoint_name
     *
     * @mbggenerated Wed Dec 27 16:30:27 CST 2017
     */
    public String getViewpointName() {
        return viewpointName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_viewpoint.viewpoint_name
     *
     * @param viewpointName the value for tb_viewpoint.viewpoint_name
     *
     * @mbggenerated Wed Dec 27 16:30:27 CST 2017
     */
    public void setViewpointName(String viewpointName) {
        this.viewpointName = viewpointName == null ? null : viewpointName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_viewpoint.star_level
     *
     * @return the value of tb_viewpoint.star_level
     *
     * @mbggenerated Wed Dec 27 16:30:27 CST 2017
     */
    public String getStarLevel() {
        return starLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_viewpoint.star_level
     *
     * @param starLevel the value for tb_viewpoint.star_level
     *
     * @mbggenerated Wed Dec 27 16:30:27 CST 2017
     */
    public void setStarLevel(String starLevel) {
        this.starLevel = starLevel == null ? null : starLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_viewpoint.score
     *
     * @return the value of tb_viewpoint.score
     *
     * @mbggenerated Wed Dec 27 16:30:27 CST 2017
     */
    public Double getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_viewpoint.score
     *
     * @param score the value for tb_viewpoint.score
     *
     * @mbggenerated Wed Dec 27 16:30:27 CST 2017
     */
    public void setScore(Double score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_viewpoint.address
     *
     * @return the value of tb_viewpoint.address
     *
     * @mbggenerated Wed Dec 27 16:30:27 CST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_viewpoint.address
     *
     * @param address the value for tb_viewpoint.address
     *
     * @mbggenerated Wed Dec 27 16:30:27 CST 2017
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_viewpoint.introduction
     *
     * @return the value of tb_viewpoint.introduction
     *
     * @mbggenerated Wed Dec 27 16:30:27 CST 2017
     */
    public String getIntroduction() {
        return introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_viewpoint.introduction
     *
     * @param introduction the value for tb_viewpoint.introduction
     *
     * @mbggenerated Wed Dec 27 16:30:27 CST 2017
     */
    public void setIntroduction(String introduction) {
        this.introduction = introduction == null ? null : introduction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_viewpoint.note
     *
     * @return the value of tb_viewpoint.note
     *
     * @mbggenerated Wed Dec 27 16:30:27 CST 2017
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_viewpoint.note
     *
     * @param note the value for tb_viewpoint.note
     *
     * @mbggenerated Wed Dec 27 16:30:27 CST 2017
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }


    public List<String> getImageUrls() {
        return imageUrls;
    }

    public void setImageUrls(List<String> imageUrls) {
        this.imageUrls = imageUrls;
    }

    public List<Ticket> getTickets() {
        return tickets;
    }

    public void setTickets(List<Ticket> tickets) {
        this.tickets = tickets;
    }

    public List<Route> getRoutes() {
        return routes;
    }

    public void setRoutes(List<Route> routes) {
        this.routes = routes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_viewpoint.exp_content1
     *
     * @return the value of tb_viewpoint.exp_content1
     *
     * @mbggenerated Wed Dec 27 16:30:27 CST 2017
     */
    public String getExpContent1() {
        return expContent1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_viewpoint.exp_content1
     *
     * @param expContent1 the value for tb_viewpoint.exp_content1
     *
     * @mbggenerated Wed Dec 27 16:30:27 CST 2017
     */
    public void setExpContent1(String expContent1) {
        this.expContent1 = expContent1 == null ? null : expContent1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_viewpoint.exp_content2
     *
     * @return the value of tb_viewpoint.exp_content2
     *
     * @mbggenerated Wed Dec 27 16:30:27 CST 2017
     */
    public String getExpContent2() {
        return expContent2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_viewpoint.exp_content2
     *
     * @param expContent2 the value for tb_viewpoint.exp_content2
     *
     * @mbggenerated Wed Dec 27 16:30:27 CST 2017
     */
    public void setExpContent2(String expContent2) {
        this.expContent2 = expContent2 == null ? null : expContent2.trim();
    }
}