package com.trip.mapper;

import com.trip.entity.Business;

import java.util.Map;

public interface BusinessMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business
     *
     * @mbggenerated Sun Dec 24 20:40:23 CST 2017
     */
    int deleteByPrimaryKey(Integer businessId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business
     *
     * @mbggenerated Sun Dec 24 20:40:23 CST 2017
     */
    int insert(Business record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business
     *
     * @mbggenerated Sun Dec 24 20:40:23 CST 2017
     */
    int insertSelective(Business record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business
     *
     * @mbggenerated Sun Dec 24 20:40:23 CST 2017
     */
    Business selectByPrimaryKey(Integer businessId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business
     *
     * @mbggenerated Sun Dec 24 20:40:23 CST 2017
     */
    int updateByPrimaryKeySelective(Business record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business
     *
     * @mbggenerated Sun Dec 24 20:40:23 CST 2017
     */
    int updateByPrimaryKey(Business record);

    Business login(Map<String,Object> param);

}