package com.trip.mapper;

import com.trip.entity.Dishes;

import java.util.List;

public interface DishesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dishes
     *
     * @mbggenerated Wed Dec 27 11:16:14 CST 2017
     */
    int deleteByPrimaryKey(Integer dishesId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dishes
     *
     * @mbggenerated Wed Dec 27 11:16:14 CST 2017
     */
    int insert(Dishes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dishes
     *
     * @mbggenerated Wed Dec 27 11:16:14 CST 2017
     */
    int insertSelective(Dishes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dishes
     *
     * @mbggenerated Wed Dec 27 11:16:14 CST 2017
     */
    Dishes selectByPrimaryKey(Integer dishesId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dishes
     *
     * @mbggenerated Wed Dec 27 11:16:14 CST 2017
     */
    int updateByPrimaryKeySelective(Dishes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dishes
     *
     * @mbggenerated Wed Dec 27 11:16:14 CST 2017
     */
    int updateByPrimaryKey(Dishes record);

    List<Dishes> queryByCondition(Dishes dishes);
}