package com.trip.mapper;

import com.trip.entity.Restaurant;

public interface RestaurantMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_restaurant
     *
     * @mbggenerated Wed Dec 27 11:16:14 CST 2017
     */
    int deleteByPrimaryKey(Integer restaurantId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_restaurant
     *
     * @mbggenerated Wed Dec 27 11:16:14 CST 2017
     */
    int insert(Restaurant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_restaurant
     *
     * @mbggenerated Wed Dec 27 11:16:14 CST 2017
     */
    int insertSelective(Restaurant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_restaurant
     *
     * @mbggenerated Wed Dec 27 11:16:14 CST 2017
     */
    Restaurant selectByPrimaryKey(Integer restaurantId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_restaurant
     *
     * @mbggenerated Wed Dec 27 11:16:14 CST 2017
     */
    int updateByPrimaryKeySelective(Restaurant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_restaurant
     *
     * @mbggenerated Wed Dec 27 11:16:14 CST 2017
     */
    int updateByPrimaryKey(Restaurant record);
}