package com.trip.mapper;

import com.trip.entity.Route;

public interface RouteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_route
     *
     * @mbggenerated Wed Dec 27 16:30:27 CST 2017
     */
    int deleteByPrimaryKey(Integer routeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_route
     *
     * @mbggenerated Wed Dec 27 16:30:27 CST 2017
     */
    int insert(Route record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_route
     *
     * @mbggenerated Wed Dec 27 16:30:27 CST 2017
     */
    int insertSelective(Route record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_route
     *
     * @mbggenerated Wed Dec 27 16:30:27 CST 2017
     */
    Route selectByPrimaryKey(Integer routeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_route
     *
     * @mbggenerated Wed Dec 27 16:30:27 CST 2017
     */
    int updateByPrimaryKeySelective(Route record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_route
     *
     * @mbggenerated Wed Dec 27 16:30:27 CST 2017
     */
    int updateByPrimaryKey(Route record);
}