package com.trip.mapper;

import com.trip.entity.Ticket;

public interface TicketMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ticket
     *
     * @mbggenerated Wed Dec 27 16:30:27 CST 2017
     */
    int deleteByPrimaryKey(Integer ticketId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ticket
     *
     * @mbggenerated Wed Dec 27 16:30:27 CST 2017
     */
    int insert(Ticket record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ticket
     *
     * @mbggenerated Wed Dec 27 16:30:27 CST 2017
     */
    int insertSelective(Ticket record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ticket
     *
     * @mbggenerated Wed Dec 27 16:30:27 CST 2017
     */
    Ticket selectByPrimaryKey(Integer ticketId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ticket
     *
     * @mbggenerated Wed Dec 27 16:30:27 CST 2017
     */
    int updateByPrimaryKeySelective(Ticket record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ticket
     *
     * @mbggenerated Wed Dec 27 16:30:27 CST 2017
     */
    int updateByPrimaryKey(Ticket record);
}