package com.trip.mapper;

import com.trip.entity.Viewpoint;

public interface ViewpointMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_viewpoint
     *
     * @mbggenerated Wed Dec 27 16:30:27 CST 2017
     */
    int deleteByPrimaryKey(Integer viewpointId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_viewpoint
     *
     * @mbggenerated Wed Dec 27 16:30:27 CST 2017
     */
    int insert(Viewpoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_viewpoint
     *
     * @mbggenerated Wed Dec 27 16:30:27 CST 2017
     */
    int insertSelective(Viewpoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_viewpoint
     *
     * @mbggenerated Wed Dec 27 16:30:27 CST 2017
     */
    Viewpoint selectByPrimaryKey(Integer viewpointId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_viewpoint
     *
     * @mbggenerated Wed Dec 27 16:30:27 CST 2017
     */
    int updateByPrimaryKeySelective(Viewpoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_viewpoint
     *
     * @mbggenerated Wed Dec 27 16:30:27 CST 2017
     */
    int updateByPrimaryKey(Viewpoint record);
}